# Generated by Django 5.2.3 on 2025-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
