# Generated by Django 5.2.3 on 2025-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password hash'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
