# Generated by Django 5.2.3 on 2025-06-27 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(verbose_name='source text')),
                ('translated_text', models.TextField(verbose_name='translated text')),
                ('source_lang', models.CharField(choices=[('EN', 'English'), ('UK', 'Ukrainian'), ('FR', 'French'), ('GE', 'German')], max_length=15, verbose_name='source language')),
                ('target_lang', models.CharField(choices=[('EN', 'English'), ('UK', 'Ukrainian'), ('FR', 'French'), ('GE', 'German')], max_length=15, verbose_name='target language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='payments.payment', verbose_name='payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'translation',
                'verbose_name_plural': 'translations',
                'db_table': 'translations',
                'indexes': [models.Index(fields=['created_at'], name='translation_created_035e0e_idx')],
            },
        ),
    ]
