# Generated by Django 5.2.3 on 2025-06-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='source_lang',
            field=models.CharField(choices=[('EN', 'English'), ('UK', 'Ukrainian'), ('FR', 'French'), ('GE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian'), ('PL', 'Polish')], max_length=15, verbose_name='source language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='target_lang',
            field=models.CharField(choices=[('EN', 'English'), ('UK', 'Ukrainian'), ('FR', 'French'), ('GE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian'), ('PL', 'Polish')], max_length=15, verbose_name='target language'),
        ),
    ]
