# Generated by Django 5.2.3 on 2025-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_alter_translation_source_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='source_lang',
            field=models.CharField(choices=[('EN', 'English'), ('UK', 'Ukrainian'), ('FR', 'French'), ('GE', 'German'), ('ES', 'Spanish')], max_length=15, verbose_name='source language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='target_lang',
            field=models.CharField(choices=[('EN', 'English'), ('UK', 'Ukrainian'), ('FR', 'French'), ('GE', 'German'), ('ES', 'Spanish')], max_length=15, verbose_name='target language'),
        ),
    ]
