# Generated by Django 5.2.3 on 2025-06-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
        ('translations', '0003_alter_translation_source_lang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('source_lang', models.CharField(max_length=5000)),
                ('target_lang', models.CharField(max_length=5000)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_translation', to='payments.payment')),
            ],
        ),
    ]
